version: '3'
services:
    web:
        image: nginx
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        ports:
            - 8080:80
        restart: always
        depends_on:
            - php
        container_name: brewme-nginx
    php:
        image: php:7.2-fpm
        restart: always
        volumes:
            - .:/var/www/html
        depends_on:
            - composer
            - db
        container_name: brewme-php
    db:
        image: mysql:5.7.23
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: Password
        container_name: brewme-db
    composer:
        image: composer
        volumes:
            - .:/app
        command: install